export interface MathNoteContent {
  id: string;
  title: string;
  tagIds: string[];
  sectionTagIds?: Record<string, string[]>;
  markdown: string;
}

export const MATH_NOTES: MathNoteContent[] = [
  {
    id: 'node-math-functions-trigonometry',
    title: 'Functions · Graphs & Trigonometry',
    tagIds: ['tag-math-functions'],
    sectionTagIds: { 'sec-trig-functions': ['tag-math-trigonometry'] },
    markdown: [
      '<!-- nodal-panel:sec-function-basics:visible -->',
      '## Functions and graphs',
      'A function assigns each input in its domain exactly one output.',
      'The domain lists allowed inputs; the range lists outputs the function actually produces.',
      'For $f(x)=x^2$, both $x=2$ and $x=-2$ give $4$, so a function need not be one-to-one.',
      '',
      '<!-- nodal-panel:sec-function-transformations:visible -->',
      '## Transformations',
      'For $y=a f(x-h)+k$, $h$ moves the graph horizontally, $k$ moves it vertically, and $a$ stretches or reflects the output.',
      'Check one point after transforming instead of memorizing a direction by name alone.',
      '',
      '<!-- nodal-panel:sec-trig-functions:visible -->',
      '## Sine and cosine',
      'On the unit circle, $\\cos \\theta$ is the x-coordinate and $\\sin \\theta$ is the y-coordinate.',
      'Both repeat every $2\\pi$ radians. The identity $\\sin^2\\theta+\\cos^2\\theta=1$ comes from the unit circle.',
      'At $\\theta=\\pi/2$, sine is $1$ and cosine is $0$.',
    ].join('\n'),
  },
  {
    id: 'node-math-calculus-chain-rule',
    title: 'Calculus · Derivatives & the Chain Rule',
    tagIds: ['tag-math-calculus'],
    markdown: [
      '<!-- nodal-panel:sec-derivative-meaning:visible -->',
      '## What a derivative measures',
      'A derivative is an instantaneous rate of change: the slope of the tangent line at a point.',
      'If $s(t)$ is position, then $s\'(t)$ is velocity.',
      '',
      '<!-- nodal-panel:sec-chain-rule:visible -->',
      '## Chain rule',
      'When one function sits inside another, differentiate the outside and multiply by the derivative of the inside.',
      '',
      '$$',
      '\\frac{d}{dx}f(g(x))=f\'(g(x))g\'(x)',
      '$$',
      '',
      'For $y=\\sin(x^2)$, the outside derivative is cosine and the inside derivative is $2x$.',
      '',
      '$$',
      '\\frac{dy}{dx}=2x\\cos(x^2)',
      '$$',
      '',
      '<!-- nodal-panel:sec-chain-rule-check:visible -->',
      '## A quick self-check',
      'If the inside were $x^2+3x$, the final answer would need the factor $2x+3$.',
      'Common error: writing only $\\cos(x^2)$ and forgetting the derivative of the inner function.',
    ].join('\n'),
  },
  {
    id: 'node-math-linear-algebra',
    title: 'Linear Algebra · Vectors & Matrices',
    tagIds: ['tag-math-linear-algebra'],
    markdown: [
      '<!-- nodal-panel:sec-vectors:visible -->',
      '## Vectors',
      'A vector can represent a displacement or a list of coordinates. Add vectors component by component.',
      'The dot product $u\\cdot v$ is a scalar. For $u=(1,2)$ and $v=(3,4)$, $u\\cdot v=1(3)+2(4)=11$.',
      '',
      '<!-- nodal-panel:sec-matrix-transformations:visible -->',
      '## Matrices as transformations',
      'A matrix sends an input vector to an output vector. Its columns show where the basis vectors go.',
      'The matrix-vector product requires matching inner dimensions: an $m\\times n$ matrix takes an $n$-component vector and produces an $m$-component vector.',
      '',
      '<!-- nodal-panel:sec-determinant:visible -->',
      '## Determinant and invertibility',
      'For a $2\\times2$ matrix with rows $(a,b)$ and $(c,d)$, the determinant is $ad-bc$.',
      'A zero determinant means the transformation collapses area and the matrix has no inverse.',
    ].join('\n'),
  },
  {
    id: 'node-math-discrete-mathematics',
    title: 'Discrete Mathematics · Logic & Proof',
    tagIds: ['tag-math-discrete'],
    markdown: [
      '<!-- nodal-panel:sec-propositions:visible -->',
      '## Propositions and implication',
      'A proposition is a statement with a truth value. The implication $P\\Rightarrow Q$ is false only when $P$ is true and $Q$ is false.',
      'Its contrapositive $\\neg Q\\Rightarrow\\neg P$ has the same truth value; its converse $Q\\Rightarrow P$ need not.',
      '',
      '<!-- nodal-panel:sec-sets:visible -->',
      '## Sets',
      'The union $A\\cup B$ contains elements in either set. The intersection $A\\cap B$ contains elements in both.',
      'If $A\\subseteq B$, every element of $A$ is in $B$. The empty set is a subset of every set.',
      '',
      '<!-- nodal-panel:sec-induction:visible -->',
      '## Mathematical induction',
      'Prove a base case, then assume the statement for $n=k$ and use that assumption to prove it for $n=k+1$.',
      'The inductive step must show why the next case follows; checking several starting values is not a proof.',
    ].join('\n'),
  },
];
