import { useState } from 'react';
import { db } from '../../db/database';
import { Modal } from '../../components/ui';
import { validatePracticePackage } from '../../domain/practiceProtocol';
import type { KnowledgeNode, RetrievalTarget } from '../../domain/types';
import type { NotePanel } from '../../domain/notePanels';
import { createEmptyCard, cardToMemoryState } from '../../repositories/reviewRepository';

interface PracticeImportDialogProps {
  open: boolean;
  node: KnowledgeNode;
  sections: NotePanel[];
  onClose: () => void;
  onImportSuccess: (targetIds: string[]) => void;
}

export function PracticeImportDialog({ open, node, sections, onClose, onImportSuccess }: PracticeImportDialogProps) {
  const [jsonText, setJsonText] = useState('');
  const [busy, setBusy] = useState(false);
  const [statusError, setStatusError] = useState('');

  if (!open) return null;

  const validation = jsonText.trim() ? validatePracticePackage(jsonText, node.id) : null;
  const pkg = validation?.package;
  const errors = validation && !validation.valid ? validation.errors : [];

  const handlePasteFromClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (text) {
        setJsonText(text);
        setStatusError('');
      }
    } catch {
      setStatusError('Clipboard access denied. Please paste directly into the text box below.');
    }
  };

  const handleImport = async () => {
    if (!pkg) return;
    setBusy(true);
    setStatusError('');

    try {
      const importedTargetIds: string[] = [];
      const timestamp = Date.now();

      await db.transaction('rw', [db.retrievalTargets, db.memoryStates], async () => {
        for (const card of pkg.cards) {
          const targetId = card.id;
          importedTargetIds.push(targetId);

          const existingTarget = await db.retrievalTargets.get(targetId);

          let promptMarkdown = '';
          let expectedEvidenceMarkdown = '';
          let practiceType: RetrievalTarget['practiceType'] = card.type;

          if (card.type === 'flashcard') {
            promptMarkdown = card.frontMarkdown.trim();
            expectedEvidenceMarkdown = card.backMarkdown.trim();
          } else if (card.type === 'choice') {
            promptMarkdown = card.frontMarkdown.trim();
            expectedEvidenceMarkdown = card.explanationMarkdown.trim();
          } else if (card.type === 'cloze') {
            promptMarkdown = card.promptMarkdown.trim();
            expectedEvidenceMarkdown = card.explanationMarkdown.trim();
          }

          const targetData: RetrievalTarget = {
            id: targetId,
            kind: 'atomic_fact',
            status: 'active',
            sourceType: 'node',
            sourceId: node.id,
            promptMarkdown,
            expectedEvidenceMarkdown,
            presentation: card.type === 'cloze' ? 'cloze' : 'question',
            practiceType,
            sectionId: card.sectionId ?? null,
            ...(card.type === 'choice' ? { options: card.options, correctOptionId: card.correctOptionId, explanationMarkdown: card.explanationMarkdown } : {}),
            ...(card.type === 'cloze' ? { blanks: card.blanks, explanationMarkdown: card.explanationMarkdown } : {}),
            revision: (existingTarget?.revision ?? 0) + 1,
            createdAt: existingTarget?.createdAt ?? timestamp,
            updatedAt: timestamp,
          };

          await db.retrievalTargets.put(targetData);

          // If MemoryState does not exist, initialize it
          const existingMemory = await db.memoryStates.get(targetId);
          if (!existingMemory) {
            const emptyCard = createEmptyCard(new Date(timestamp));
            const state = cardToMemoryState(targetId, emptyCard, timestamp);
            await db.memoryStates.add(state);
          }
        }
      });

      onImportSuccess(importedTargetIds);
      onClose();
    } catch (e) {
      setStatusError(`Import failed: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      setBusy(false);
    }
  };

  const getSectionLabel = (sectionId: string | null) => {
    if (!sectionId) return 'Global (Whole note)';
    const sec = sections.find((s) => s.id === sectionId);
    return sec ? `Section "${sectionId}"` : `Section "${sectionId}" (unknown)`;
  };

  return (
    <Modal open={open} onClose={onClose} title="Import Practice Questions" width={640}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
        <p style={{ fontSize: 'var(--font-sm)', color: 'var(--text-secondary)', margin: 0 }}>
          Paste JSON generated by your AI tool adhering to the <code>nodal.practice.v1</code> schema.
        </p>

        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <button type="button" className="ghost" onClick={handlePasteFromClipboard} style={{ fontSize: 'var(--font-xs)', padding: '4px 10px' }}>
            Paste from clipboard
          </button>
        </div>

        <textarea
          aria-label="Practice JSON input"
          value={jsonText}
          onChange={(e) => setJsonText(e.target.value)}
          placeholder={`{\n  "schemaVersion": "nodal.practice.v1",\n  "noteId": "${node.id}",\n  "sourceRevision": "${node.updatedAt || Date.now()}",\n  "cards": [...]\n}`}
          rows={10}
          style={{
            fontFamily: 'monospace',
            fontSize: 'var(--font-xs)',
            width: '100%',
            padding: 'var(--space-2)',
            borderRadius: 'var(--radius-md)',
            border: '1px solid var(--border)',
            background: 'var(--surface)',
            color: 'var(--text)',
            resize: 'vertical',
          }}
        />

        {errors.length > 0 && (
          <div role="alert" style={{ background: '#fdf2f1', border: '1px solid #e59994', borderRadius: '8px', padding: '10px 14px', fontSize: '13px', color: '#b8332a' }}>
            <strong style={{ display: 'block', marginBottom: '4px' }}>Validation errors ({errors.length}):</strong>
            <ul style={{ margin: 0, paddingLeft: '18px' }}>
              {errors.slice(0, 5).map((err, i) => (
                <li key={i}>{err}</li>
              ))}
              {errors.length > 5 && <li>...and {errors.length - 5} more errors</li>}
            </ul>
          </div>
        )}

        {statusError && (
          <p role="alert" style={{ color: 'var(--danger)', fontSize: 'var(--font-sm)', margin: 0 }}>
            {statusError}
          </p>
        )}

        {pkg && (
          <div style={{ background: 'var(--surface-secondary, rgba(0,0,0,0.03))', border: '1px solid var(--border)', borderRadius: '8px', padding: '12px 14px', fontSize: '13px' }}>
            <strong style={{ color: 'var(--accent)', display: 'block', marginBottom: '6px' }}>
              ✓ Valid package: {pkg.cards.length} {pkg.cards.length === 1 ? 'card' : 'cards'} ready to import
            </strong>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', maxHeight: '160px', overflowY: 'auto' }}>
              {pkg.cards.map((c, i) => (
                <div key={c.id || i} style={{ display: 'flex', justifyContent: 'space-between', padding: '3px 0', borderBottom: '1px solid var(--border-light, #eee)' }}>
                  <span>
                    <strong style={{ marginRight: '6px' }}>{i + 1}. [{c.type.toUpperCase()}]</strong>
                    <span>{c.type === 'cloze' ? c.promptMarkdown.slice(0, 40) : c.frontMarkdown.slice(0, 40)}...</span>
                  </span>
                  <small style={{ color: 'var(--text-muted)' }}>{getSectionLabel(c.sectionId)}</small>
                </div>
              ))}
            </div>
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 'var(--space-2)', marginTop: 'var(--space-2)' }}>
          <button type="button" className="ghost" onClick={onClose} disabled={busy}>
            Cancel
          </button>
          <button
            type="button"
            className="primary"
            onClick={handleImport}
            disabled={!pkg || busy}
          >
            {busy ? 'Importing…' : `Import ${pkg ? `${pkg.cards.length} cards` : 'cards'}`}
          </button>
        </div>
      </div>
    </Modal>
  );
}
